// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtuvywkanemnalsztobx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0dXZ5d2thbmVtbmFsc3p0b2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjM5MjcsImV4cCI6MjA2OTY5OTkyN30.rThBOnOaF5g3eLG1ywOfrTY19LJvhe4XMbfBx2fHSyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});